#
#spring:
#  mail:
#    host: smtp.gmail.com
#    username: ashishgrd914@gmail.com
#    password: qubghffzcqpgzjpq
#    port: 587
#    properties:
#      mail:
#        smtp:
#          starttls:
#            enable: true
#          auth: true